import { Client } from "@notionhq/client";
const token = process.env.NOTION_TOKEN;
const databaseId = process.env.NOTION_DATABASE_ID;

const notion = new Client({
  auth: token,
});

//get all pages(posts) in Notion database
export const getDatabase = async () => {
  const response = await notion.databases.query({
    database_id: databaseId,
    // Filter out posts not checked to publish.
    filter: {
      and: [
        {
          property: "Published",
          checkbox: {
            equals: true,
          },
        },
      ],
    },
    // Sort posts in descending order based on the Date column.
    sorts: [
      {
        property: "Date",
        direction: "descending",
      },
    ],
  });
  return response.results;
};

//get values of single or multiple properties from page(post) using property_id value
//e.g. property_id = {Author: id: *uuid generated by notion*}
export const getPropertyValues = async (
  pageId,
  propertyIdObj,
  filterProperty
) => {
  let response = {};
  for (const property in propertyIdObj) {
    let propertyData = await notion.pages.properties.retrieve({
      page_id: pageId,
      property_id: propertyIdObj?.[property].id || propertyIdObj.id,
    });
    response[filterProperty ? filterProperty : property] = propertyData;
  }
  return response;
};

//get list of all properties including their value for each page(post) in Notion database
//properties = e.g. Title, Tags, Slug, Author, etc...
export const getAllPropertyValues = async () => {
  let propertyData = [];
  const pageList = await getDatabase();

  for (let p of pageList) {
    const data = await getPropertyValues(p.id, p.properties);
    propertyData.push(data);
  }
  return propertyData;
};

//filter database to get single page(post) by slug name
export const getPageBySlug = async (slug) => {
  const response = await notion.databases.query({
    database_id: databaseId,
    page_size: 1,
    filter: {
      property: "Slug",
      rich_text: {
        contains: slug,
      },
    },
  });
  return response.results[0];
};

//get the content of a single page(post) using blockId (aka page_id)
//content data is organized into multiple blocks (sections)
export const getPostBlockContent = async (blockId) => {
  let blockResponse = await notion.blocks.children.list({
    block_id: blockId,
    page_size: 25,
  });

  return blockResponse;
};

//get data of the page(post) author (name, profile photo)
export const getUser = async (userId) => {
  const response = await notion.users.retrieve({ user_id: userId });
  return response;
};
